import type { Concept, Misconception, Probe, TopicPack } from '../engine/types';

const conceptRows = [
  ['acceleration', 'Force changes velocity', 'Net force causes acceleration, not velocity.', 'Distinguishes velocity from change in velocity; F = ma alone is partial.'],
  ['inertia', 'Motion needs no fuel', 'An object keeps a constant velocity when the net force is zero.', 'Explicitly permits nonzero constant velocity without net force.'],
  ['interaction', 'A push is an interaction', 'After release, a thrown object carries no stored force from the thrower.', 'Rejects an internal impetus or a force that gets used up after release.'],
  ['fall', 'Mass does not set falling speed', 'In a vacuum, objects fall with the same acceleration regardless of mass.', 'Explicit comparison of unequal masses without drag.'],
  ['pairs', 'Equal and opposite forces', 'Two interacting objects exert equal and opposite forces on each other, regardless of their masses.', 'States equality on different objects, including unequal masses.'],
  ['circular', 'Turning takes inward force', 'Circular motion requires a net force toward the center, not an outward force.', 'Identifies inward net force in an inertial frame.'],
  ['normal', 'Surfaces exert forces', 'An inanimate surface exerts a normal contact force on an object it supports.', 'An explicit supporting force from a table, floor, or similar surface.'],
  ['gravity', 'Gravity needs no air', 'Gravity acts in a vacuum and continues to pull downward throughout a ball’s flight.', 'Includes gravity in vacuum and throughout ascent, top, and descent.'],
  ['direction', 'Acceleration can oppose motion', 'Velocity and acceleration can point in opposite directions, and zero velocity does not imply zero acceleration.', 'Includes both slowing motion and the instant at the top of a throw.'],
  ['friction', 'Friction opposes slipping', 'Static friction opposes relative slipping at a contact, so it can point in the direction of an object’s motion.', 'Distinguishes slipping at contact from center-of-mass motion.'],
] as const;
export const concepts: Concept[] = conceptRows.map(([id, label, statement, probeHint]) => ({ id, label, statement, probeHint }));
const misconceptionRows = [
  ['impetus', 'Stored push', 'I think a thrown object carries the thrower’s force inside it', 'interaction', 'McCloskey (1983); Halloun & Hestenes (1985)'],
  ['sustaining', 'Motion needs a force', 'I think any moving object needs a continuing force in its direction of travel', 'inertia', 'Halloun & Hestenes (1985)'],
  ['mass-fall', 'Heavier falls faster', 'I think a heavier object accelerates faster in free fall', 'fall', 'Halloun & Hestenes (1985)'],
  ['velocity-force', 'Force follows speed', 'I think net force is proportional to speed rather than acceleration', 'acceleration', 'Halloun & Hestenes (1985)'],
  ['unequal-pairs', 'Bigger means stronger', 'I think the more massive object exerts the larger interaction force', 'pairs', 'Hestenes, Wells & Swackhamer (1992), taxonomy only'],
  ['used-up', 'The push runs out', 'I think the upward force of a throw gets used up until the object turns around', 'interaction', 'McCloskey (1983); Halloun & Hestenes (1985)'],
  ['centrifugal', 'An outward turning force', 'I think a real outward net force keeps an object moving in a circle', 'circular', 'McCloskey (1983)'],
  ['no-motion', 'No force, no motion', 'I think removing all forces makes an object stop immediately', 'inertia', 'Halloun & Hestenes (1985)'],
  ['animate-normal', 'Only active things push', 'I think a motionless inanimate surface cannot exert an upward force', 'normal', 'Minstrell (1982), Explaining the at rest condition of an object'],
  ['air-gravity', 'Air makes things fall', 'I think gravity needs air to pull an object down', 'gravity', 'Hestenes, Wells & Swackhamer (1992), taxonomy only'],
  ['direction', 'Motion and acceleration align', 'I think acceleration always points along velocity and vanishes when velocity is zero', 'direction', 'Trowbridge & McDermott (1981)'],
  ['rolling-friction', 'Friction always points back', 'I think friction must point backward whenever an object is moving forward', 'friction', 'Besson, Borghi, De Ambrosis & Mascheretti (2007), How to teach friction'],
] as const;
export const misconceptions: Misconception[] = misconceptionRows.map(([id, label, belief, conceptId, citation]) => ({ id, label, belief, attachedTo: [conceptId], repair: concepts.find(c => c.id === conceptId)!.statement, citation }));
function q(id: string, stem: string, choices: string[], wrong: Record<string, string>, targets: string[]): Probe {
  return { id, stem, choices: choices.map((text, i) => ({ id: String.fromCharCode(65 + i), text })), correct: 'A', predicted: Object.fromEntries(misconceptions.map(m => [m.id, wrong[m.id] ?? '*'])), targets };
}
// Original authored items, not copied or adapted verbatim from the FCI.
// A is canonical here; presentation shuffles positions without changing choice IDs.
const probes: Probe[] = [
  q('p01', 'A ball is rising after leaving a hand. Ignore air resistance. Which account best describes its forces?', ['Only gravity acts, downward.', 'A stored upward push and gravity act together.', 'A continuing upward net force is required because it is moving upward.', 'There is an upward acceleration because the velocity is upward.'], { impetus: 'B', 'used-up': 'B', sustaining: 'C', 'velocity-force': 'C', direction: 'D' }, ['interaction', 'acceleration', 'direction']),
  q('p02', 'A puck crosses a level frictionless surface after a brief push. What happens after contact with the hand ends?', ['It continues at constant speed; the push is no longer a force.', 'A force stored in the puck keeps it moving unchanged.', 'The stored push gradually runs out and it slows.', 'It stops immediately because nothing is pushing.'], { impetus: 'B', sustaining: 'B', 'velocity-force': 'B', 'used-up': 'C', 'no-motion': 'D' }, ['inertia', 'interaction']),
  q('p03', 'A heavy and a light bead are released together inside an evacuated tube. What happens?', ['Both fall with the same acceleration.', 'The heavy bead accelerates faster.', 'Neither falls because there is no air.', 'They both need a downward shove to begin falling.'], { 'mass-fall': 'B', 'unequal-pairs': 'B', 'air-gravity': 'C', 'no-motion': 'D' }, ['fall', 'gravity']),
  q('p04', 'A rover accelerates forward without its powered wheels slipping. Which statement about horizontal forces is right?', ['The ground pushes the powered wheels forward by static friction.', 'Friction must point backward because the rover moves forward.', 'The ground cannot push because it is not an active agent.', 'The force must grow in direct proportion to the rover’s speed.'], { 'rolling-friction': 'B', 'animate-normal': 'C', 'velocity-force': 'D' }, ['friction', 'normal', 'acceleration']),
  q('p05', 'A small magnet and a massive steel cart attract each other on frictionless tracks. Which account is right?', ['Their forces are equal; the lighter object accelerates more.', 'The massive cart exerts the larger force.', 'The faster-moving object must experience the larger force.', 'Neither can exert force unless a person actively pushes it.'], { 'unequal-pairs': 'B', 'mass-fall': 'B', 'velocity-force': 'C', 'animate-normal': 'D' }, ['pairs', 'acceleration', 'normal']),
  q('p06', 'A tethered capsule moves at steady speed in a circle in a vacuum. Seen from a fixed outside camera, its net force points…', ['Toward the circle’s center.', 'Outward from the center.', 'Along its instantaneous direction of travel.', 'Nowhere: there is no force without air.'], { centrifugal: 'B', sustaining: 'C', 'velocity-force': 'C', direction: 'C', 'air-gravity': 'D' }, ['circular', 'direction']),
  q('p07', 'At the very top of a vertical toss in a vacuum, which statement is right?', ['Velocity is zero; acceleration is downward.', 'Both velocity and acceleration are zero.', 'The stored upward force still acts along with gravity.', 'Gravity is absent because there is no air.'], { direction: 'B', 'velocity-force': 'B', 'used-up': 'B', impetus: 'C', 'air-gravity': 'D' }, ['direction', 'gravity', 'interaction']),
  q('p08', 'A delivery robot moves right but slows down on a straight path. Its net force is…', ['To the left.', 'To the right because it is moving right.', 'Zero because the force from starting has been used up.', 'Impossible to describe: motion requires an increasing forward force.'], { direction: 'B', sustaining: 'B', 'velocity-force': 'B', impetus: 'B', 'used-up': 'C', 'no-motion': 'D' }, ['acceleration', 'direction']),
  q('p09', 'A stone on a cord moves in a circle. The cord breaks. Ignore gravity for this brief moment. The stone then…', ['Moves along the tangent at constant velocity.', 'Moves directly outward from the circle’s center.', 'Keeps curving because the turning push is stored.', 'Stops immediately when the cord’s force vanishes.'], { centrifugal: 'B', impetus: 'C', 'no-motion': 'D', sustaining: 'D' }, ['circular', 'inertia', 'interaction']),
  q('p10', 'A book rests on a shelf in an airless room. What balances its weight?', ['An upward contact force exerted by the shelf.', 'Nothing: a passive shelf cannot exert force.', 'No balance is needed because gravity needs air.', 'An upward force stored in the book when it was placed.'], { 'animate-normal': 'B', 'air-gravity': 'C', impetus: 'D' }, ['normal', 'gravity']),
  q('p11', 'Two carts of equal mass pass a sensor at different constant speeds on frictionless level tracks. Their horizontal net forces are…', ['Both zero.', 'Larger on the faster cart.', 'Equal and forward because both carts are moving.', 'Both backward as the original pushes run out.'], { 'velocity-force': 'B', sustaining: 'C', impetus: 'C', 'used-up': 'D' }, ['acceleration', 'inertia']),
  q('p12', 'A coin has just been launched upward. Compare the thrower’s force just after release and halfway to the top.', ['It is absent at both moments.', 'It is stored in the coin and remains unchanged.', 'It is stored in the coin but becomes weaker.', 'It remains a direct contact force while the coin moves.'], { impetus: 'B', 'used-up': 'C', sustaining: 'D' }, ['interaction']),
  q('p13', 'On an airless moon, a hammer with twice a pebble’s mass is dropped beside it. Their accelerations are…', ['Equal.', 'Greater for the hammer.', 'Zero for both.'], { 'mass-fall': 'B', 'air-gravity': 'C' }, ['fall', 'gravity']),
  q('p14', 'A large tractor pulls a small trailer. Compare the force of tractor on trailer with trailer on tractor.', ['Equal in magnitude and opposite in direction.', 'The tractor’s force is larger.', 'The trailer’s force is larger.'], { 'unequal-pairs': 'B' }, ['pairs']),
  q('p15', 'A puck already moving in deep space has all external forces removed. What happens immediately?', ['It keeps its current velocity.', 'It stops.', 'It slows gradually as its push is exhausted.'], { 'no-motion': 'B', sustaining: 'B', 'used-up': 'C' }, ['inertia']),
  q('p16', 'A curved guide bends a marble’s path at constant speed. What is the direction of its acceleration?', ['Toward the inside of the bend.', 'Along its velocity.', 'Outward from the bend.'], { direction: 'B', 'velocity-force': 'B', centrifugal: 'C' }, ['circular', 'direction']),
  q('p17', 'A spring scale under a stationary stone shows a reading. The scale is…', ['Exerting an upward contact force on the stone.', 'Measuring weight without exerting any force itself.', 'Giving a reading only because air presses down.'], { 'animate-normal': 'B', 'air-gravity': 'C' }, ['normal']),
  q('p18', 'A car’s driven tire grips the road and speeds the car forward. On the tire, the road’s static friction points…', ['Forward, preventing backward slip at the contact.', 'Backward, as all friction opposes travel.', 'Nowhere, because a road cannot actively push.'], { 'rolling-friction': 'B', 'animate-normal': 'C' }, ['friction']),
  q('p19', 'A sled moves at a constant nonzero velocity. Its net force is…', ['Zero.', 'Forward, proportional to its velocity.', 'Backward.'], { sustaining: 'B', 'velocity-force': 'B' }, ['acceleration', 'inertia']),
  q('p20', 'An astronaut lets go of a tool beside a small moon. Far from air, the moon’s gravity…', ['Still acts on the tool.', 'Cannot act without air.', 'Acts only after a downward push.'], { 'air-gravity': 'B' }, ['gravity']),
  q('p21', 'For the same nonzero net force, which of two unequal masses has the larger acceleration?', ['The smaller mass.', 'The larger mass.', 'Whichever is already moving faster.'], { 'mass-fall': 'B', 'velocity-force': 'C' }, ['fall', 'acceleration']),
  q('p22', 'A ball drops from rest. A moment later, gravity points downward. Its velocity then points…', ['Downward.', 'Upward.', 'Nowhere: rest prevents gravity from starting motion.'], { 'no-motion': 'C' }, ['gravity', 'inertia']),
  q('p23', 'A pebble at rest begins to fall in a vacuum. It is acted on by…', ['Gravity.', 'No force because there is no air.', 'Only air resistance.'], { 'air-gravity': 'B' }, ['gravity']),
  q('p24', 'A suitcase sits motionless on a station floor. Is there a contact force from the floor?', ['Yes, upward.', 'No, the floor is not an active pusher.', 'Only while someone is lifting the suitcase.'], { 'animate-normal': 'B' }, ['normal']),
  q('p25', 'A space probe fires a sideways thruster while already moving forward. Its acceleration initially follows…', ['The sideways net force.', 'Its existing forward velocity.', 'An outward radial direction regardless of the thruster.'], { direction: 'B', 'velocity-force': 'B', centrifugal: 'C' }, ['direction', 'acceleration']),
  q('p26', 'A powered wheel rolls uphill without slipping. The ground can exert a forward friction force because…', ['It prevents backward relative slip at the contact point.', 'It cannot: friction must always point downhill against travel.', 'It stores a push inside the wheel.'], { 'rolling-friction': 'B', impetus: 'C' }, ['friction', 'interaction']),
  q('p27', 'A metal marble crosses a frictionless level track after being flicked. Why does it continue?', ['Inertia: no horizontal net force is needed.', 'The flick remains inside it as a force.', 'Its stored force is slowly being consumed.', 'A continuing external force must be hidden somewhere.'], { impetus: 'B', 'used-up': 'C', sustaining: 'D', 'velocity-force': 'D' }, ['interaction', 'inertia']),
  q('p28', 'A truck and a scooter compress a spring between them on level frictionless ground. During release…', ['The spring exerts equal forces; the scooter accelerates more.', 'The truck experiences a greater force because it is heavier.', 'The scooter experiences greater force because it moves faster.', 'The spring cannot exert force because it is inanimate.'], { 'unequal-pairs': 'B', 'mass-fall': 'B', 'velocity-force': 'C', 'animate-normal': 'D' }, ['pairs', 'normal', 'acceleration']),
];
export const newtonian: TopicPack = { id: 'newtonian', title: 'Newtonian force & motion', concepts, misconceptions, probes };
