'use client';
import Link from 'next/link';
import { useCallback, useState } from 'react';
import { useModal } from './useModal';
import { ArrowRight, ArrowUpRight, Mic, Play, Check, MoveUpRight, Atom, Clock3, AudioLines, X, Menu, Leaf, ScanSearch, PenLine, Sparkles } from 'lucide-react';
import { Brand, Spark } from './Brand';
import Mascot from './Mascot';
import PosteriorChart from './PosteriorChart';
import { config, prediction, seededRng, selectNextProbe, uniformPrior, updatePosterior } from '@/lib/engine';
import { newtonian as pack } from '@/lib/packs';
export default function Landing(){
 const [mobile,setMobile]=useState(false);const [demo,setDemo]=useState(false);const [demoStep,setDemoStep]=useState(0);
 const closeDemo=useCallback(()=>setDemo(false),[]);useModal(demo,closeDemo);
 const demoDist=(()=>{let d=uniformPrior(pack);const asked:string[]=[];for(let i=0;i<demoStep;i++){const p=selectNextProbe(pack.probes,d,asked,config,seededRng(1))!;d=updatePosterior(d,p,prediction('used-up',p),config);asked.push(p.id);}return d;})();
 function openDemo(){setDemoStep(0);setDemo(true);}
 return <><div className="announcement"><Sparkles size={13}/><span>A little teaching. A lot of understanding.</span><ArrowUpRight size={14}/></div><header className="site-header wrap"><Brand/><nav className={mobile?'nav-links mobile-open':'nav-links'} aria-label="Main navigation"><a href="#how-it-works" onClick={()=>setMobile(false)}>How it works</a><a href="#the-science" onClick={()=>setMobile(false)}>The science</a><a href="#our-story" onClick={()=>setMobile(false)}>Why Viva?</a></nav><div className="header-actions"><button className="text-button" onClick={openDemo}>Try a demo <ArrowUpRight size={15}/></button><Link className="button button-small" href="/session">Let’s learn <ArrowRight size={16}/></Link><button className="mobile-toggle icon-button" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
 <main><section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="green-dot"/> A FRESH WAY TO FIND YOUR AHA!</div><h1>Learn it better.<br/>Teach it to <span className="viva-word">Viva.<svg viewBox="0 0 180 18" aria-hidden="true"><path d="M3 12Q85 -2 173 8M22 16Q106 7 160 13" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/></svg></span></h1><p>You don’t really know it until you can teach it.<br className="desktop-break"/> Meet the AI student that helps you see what you<br className="desktop-break"/> understand—and what’s not quite there yet.</p><div className="hero-buttons"><Link href="/session" className="button">Take the teacher’s seat <ArrowUpRight size={19}/></Link><button className="demo-link" onClick={openDemo}><span><Play size={12} fill="currentColor"/></span>See the aha! moment</button></div><div className="hero-reassurance"><Check size={14}/> No sign-up <span>·</span><Check size={14}/> No pressure <span>·</span> Just curiosity</div></div>
 <div className="hero-art" aria-label="An illustrated preview of teaching your AI student"><div className="art-orbit"/><svg className="art-scribble" viewBox="0 0 550 500" fill="none" aria-hidden="true"><path d="M92 90C27 62 35 7 75 31C99 54 54 89 20 82M418 379C489 440 537 397 517 367C482 334 460 399 499 452" stroke="#667A56" strokeWidth="2" strokeLinecap="round"/><path d="M428 46L432 21M440 53L461 38M444 68L471 64" stroke="#38563A" strokeWidth="3" strokeLinecap="round"/><path d="M41 290L48 274L55 291L72 296L53 303L47 322L42 302L25 296Z" fill="#B7A5D1"/><path d="M457 245L462 231L468 244L481 249L467 254L463 269L457 253L443 249Z" fill="#6D8553"/></svg><div className="lesson-note"><span className="note-pin"/><div className="note-kicker">YOU, THE TEACHER</div><p>“The ball slows down<br/>because its push runs out.”</p><div className="note-wave"><AudioLines size={18}/><span>Your words are the starting point.</span></div></div><div className="mascot-wrap"><Mascot/></div><div className="student-label">a curious little<br/><em>reflection of you</em><svg viewBox="0 0 80 50"><path d="M3 5Q14 41 65 34L55 25M65 34L55 44" stroke="currentColor" strokeWidth="1.5" fill="none"/></svg></div><div className="aha-card"><div className="aha-card-header"><span className="mini-spark"><Spark/></span><span>A little gap. A big discovery.</span><span className="tiny-dots">•••</span></div><div className="mini-belief"><span>The push runs out</span><b>92%</b></div><div className="mini-track"><i/></div><div className="mini-belief light"><span>Other possibilities</span><b>8%</b></div><div className="mini-track pale"><i/></div><div className="aha-card-bottom"><span><Check size={12}/></span>Now you know exactly what to teach next.</div></div><div className="voice-sticker"><Mic size={17}/><span>Talk it out.<br/><strong>We’re listening.</strong></span></div></div></section>
 <section className="promise-strip"><span>Less memorising.</span><Spark/><span>More lightbulb moments.</span><Spark/><span>Learning that stays with you.</span></section>
 <section className="topic-section wrap" id="start-learning"><div className="section-heading"><span className="eyebrow">BIG IDEAS. SMALL BEGINNINGS.</span><h2>A little lesson.<br/>A lot to discover.</h2><p>Start with something familiar. You might be<br/>surprised by what teaching it reveals.</p></div><Link href="/session" className="topic-card"><div className="topic-card-top"><span className="topic-tag">THE FIRST CHAPTER</span><span className="round-arrow"><ArrowUpRight size={22}/></span></div><div className="atom-art"><Atom size={106} strokeWidth={.8}/><span className="atom-star">✧</span></div><div className="topic-card-copy"><span className="eyebrow">PHYSICS, WITHOUT THE PRESSURE</span><h3>What goes up,<br/>must come down. But why?</h3><p>Newtonian force & motion</p><div className="topic-meta"><span><Clock3 size={14}/> 5–8 minutes</span><span><Mic size={14}/> Speak or type</span><span>Beginner-friendly <ArrowRight size={13}/></span></div></div></Link></section>
 <section id="how-it-works" className="how-section"><div className="wrap"><div className="center-heading"><span className="eyebrow">THE ROLES ARE REVERSED. THE LEARNING IS REAL.</span><h2>You teach. Viva learns.<br/><em>You both get better.</em></h2><p>No flashcard marathons. No talking at a chatbot.<br/>Just three little steps to a deeper understanding.</p></div><div className="steps-grid"><article><div className="step-art teach-art"><div className="illustrated-note"><PenLine size={23}/><span>“Here’s how<br/>I think it works…”</span><i/></div><span className="floating-mic"><Mic size={22}/></span></div><span className="step-number">01 / TEACH</span><h3>Say it your way.</h3><p>Explain a concept like you would to a friend. Type it out or talk it through. Messy thinking is welcome here.</p></article><article><div className="step-art probe-art"><div className="illustrated-chart"><ScanSearch size={21}/><i/><i/><i/><span>Getting warmer…</span></div><Spark className="floating-spark"/></div><span className="step-number">02 / PROBE</span><h3>Find the missing piece.</h3><p>A few carefully chosen questions bring your understanding into focus. Watch the possibilities narrow in real time.</p></article><article><div className="step-art repair-art"><Mascot small/><span className="little-bubble">Oh! Now I get it.</span></div><span className="step-number">03 / REPAIR</span><h3>Make the idea click.</h3><p>Watch your student try, stumble, and try again. Add the missing idea and see what changes. That’s your aha! moment.</p></article></div><div className="center-cta"><Link className="button" href="/session">Let’s find your aha! <ArrowUpRight size={18}/></Link><span>Free to explore. Built for the curious.</span></div></div></section>
 <section id="the-science" className="science-section wrap"><div className="science-card"><span className="eyebrow"><Leaf size={15}/> A LITTLE SCIENCE BEHIND THE MAGIC</span><h2>Not made-up mistakes.<br/><em>Meaningful ones.</em></h2><p>Viva’s wrong answers aren’t random. They come from documented ideas that learners commonly struggle with. A Bayesian engine works out which belief your answers support—then your student brings it to life.</p><div className="science-pills"><span>12 researched beliefs</span><span>28 original questions</span><span>Zero AI-chosen answers</span></div><Link href="/science" className="inline-link">Look under the hood <ArrowUpRight size={17}/></Link></div><div className="science-quote"><span className="quote-mark">“</span><blockquote>When you teach,<br/>you learn twice.</blockquote><p>Viva is built around a simple idea:<br/>the clearest mirror of your knowledge<br/>is the way you explain it.</p><div className="scribble-flower"><Spark/><Spark/><Spark/></div></div></section>
 <section id="our-story" className="closing-section"><div className="wrap"><span className="eyebrow">FOR THE WONDERERS. THE WHY-ASKERS. YOU.</span><h2>You don’t need all the answers.<br/>Just a place to start.</h2><Link href="/session" className="button">Meet your student <ArrowUpRight size={18}/></Link><p>No account needed. Your session stays in this tab.</p></div></section></main><footer className="site-footer wrap"><Brand/><p>A little curiosity goes a long way.</p><div><Link href="/science">The science & our limits</Link><span>Made for aha! moments <Spark/></span></div></footer>
 {demo&&<div className="modal-backdrop" onClick={()=>setDemo(false)}><section className="demo-modal" role="dialog" aria-modal="true" aria-labelledby="demo-title" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="Close demo" onClick={()=>setDemo(false)} autoFocus><X/></button><span className="eyebrow">A 30-SECOND PEEK · NO AI CALLS</span><h2 id="demo-title">Watch an idea come into focus.</h2><p>This simulated learner believes the push from a throw runs out. Each answer gives the engine a little more evidence.</p><PosteriorChart distribution={demoDist} compact observations={demoStep}/><div className="modal-actions"><button className="button" onClick={()=>setDemoStep(s=>s===4?0:s+1)}>{demoStep===4?'Replay the demo':'Give the next answer'} <ArrowRight size={17}/></button><Link className="inline-link" href="/session?demo=1">Try the full experience <ArrowUpRight size={15}/></Link></div></section></div>}</>;
}
